language: objective-c
osx_image: xcode11.1
matrix:
    include:
        - name: "MockoloTests"
          script: swift test -Xswiftc -DDEBUG
        - name: "MockoloBinary"
          script: swift build -c release
