name: Build Actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    name: Test on ${{ matrix.os }} - ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            version: "5.10"
          - os: ubuntu-latest
            version: "6.0"
          - os: ubuntu-latest
            version: "6.1"
          - os: ubuntu-latest
            version: "6.2"
          - os: macos-latest
            version: "16.2" # Swift 6.0
          - os: macos-latest
            version: "16.4" # Swift 6.1
          - os: macos-latest
            version: "26.1" # Swift 6.2
    steps:
      - if: startsWith(matrix.os, 'ubuntu')
        uses: vapor/swiftly-action@v0.2
        with:
          toolchain: ${{ matrix.version }}
      - if: startsWith(matrix.os, 'macos')
        name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode_${{ matrix.version }}.app"

      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: swift test
        env:
          CI: 1
